### ISSUE TITLE
Sentry for PowerShell

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-powershell#3]
We can prob wrap `Sentry.dll` in a [PS Module](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_modules?view=powershell-7.4)

    PowerShell 7.4 - Built on .NET 8.0
    PowerShell 7.3 - Built on .NET 7.0
    PowerShell 7.2 (LTS-current) - Built on .NET 6.0 (LTS-current)
    PowerShell 7.1 - Built on .NET 5.0
    PowerShell 7.0 (LTS) - Built on .NET Core 3.1 (LTS)
    PowerShell 6.2 - Built on .NET Core 2.1
    PowerShell 6.1 - Built on .NET Core 2.1
    PowerShell 6.0 - Built on .NET Core 2.0

[From the docs](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.4#net-framework-vs-net-core)

We to be able to list versions we support. On Windows, it's tied to OS, so we might need to list OS versions.
Or PS versions, as [PS 5.1 for examples is built on .NET Framework 4.5.1](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-5.1) which we don't support.

> Windows PowerShell 5.1 is built on top of the .NET Framework v4.5.

We have several PowerShell scripts in the .NET/Unity repos. We can dogfood it there.

**Comment by bruno-garcia** [comment]
Icon will be added to `platformicons` so we can use on docs and wizard: https://github.com/getsentry/platformicons/pull/142

**Comment by vaind** [comment]
[PowerShell Core: resolving assembly conflicts](https://stackoverflow.com/questions/72490964/powershell-core-resolving-assembly-conflicts)

**Comment by vaind** [comment]
* [ ] SDK name
* [ ] event.sdk.packages
* [ ] release is automatically set to: `"pwsh@7.4.1 SHA: 6a98b28414948626f1b29a5e8b062e73b7ff165a+6a98b28414948626f1b29a5e8b062e73b7ff165a"` - do we want to leave that or is there a better value we can come up with automatically?
* [ ] message sending - attach script stacktrace - maybe as another "Thread"?

**Comment by vaind** [comment]
https://www.powershellgallery.com/packages/Sentry/

followups should be in new issues, or in a generic one like #27 if it's a one-liner
